name: Run Stage Scripts

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "master"
      - "main"
    paths:
      - iac/stage/infra/**

env:
  
  TF_VAR_aws_role: ${{ secrets.STAGE_ASSUME_ROLE }}

permissions: write-all

jobs:
  GetModifiedFiles:
    name: Get Modified Files
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Get Modified Files
        id: modified-files
        uses: tj-actions/changed-files@v41
        with:
          files_separator: ","
          files: |
            iac/stage/scripts/**

    outputs:
      matrix: ${{ steps.modified-files.outputs.all_changed_files }}

  RunScript:
    name: Run Script
    runs-on: ubuntu-latest
    needs: GetModifiedFiles
    strategy:
      matrix:
        FUNCTIONS: ["${{needs.GetModifiedFiles.outputs.matrix}}", none]
        exclude:
          - FUNCTIONS: none

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.STAGE_ASSUME_ROLE }}
          role-session-name: gh-actions-exe-role
          aws-region: us-east-1

      - name: Shell Linter
        uses: azohra/shell-linter@v0.6.0
        with:
          path: "iac/stage/scripts/*.sh"

